// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import "dotenv/config";
import { defineConfig } from "prisma/config";

// Select DB URL based on NODE_ENV
// Supports both environment-specific URLs (DATABASE_URL_PROD) and standard DATABASE_URL
let dbUrl: string | undefined;
if (process.env.NODE_ENV === "production") {
  dbUrl = process.env["DATABASE_URL_PROD"] || process.env["DATABASE_URL"];
} else if (process.env.NODE_ENV === "staging") {
  dbUrl = process.env["DATABASE_URL_STAGING"] || process.env["DATABASE_URL"];
} else {
  dbUrl = process.env["DATABASE_URL_DEV"] || process.env["DATABASE_URL"];
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
